---
title: "DA401"
author: "Alex Barnes"
date: "March 3, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lpSolve)
library(lpSolveAPI)
library(readr)
library(gurobi)
```

```{r}
nutrition <- read_csv("C:/Users/alex/OneDrive/Documents/DA401/data/BFPD_csv_07132018/nutrient.csv")
ndb_no <- subset(nutrition, select = c(NDB_No))
nutrition <- subset(nutrition, select = -c(X1, NDB_No))
#sub_nutrition <-t(sub_nutrition)
sub_nutrition <- nutrition[1:250,]
age <- strtoi(readline(prompt = "Enter age: "))
gender <- tolower(readline(prompt = "Enter sex(m/f): "))
height <- strtoi(readline(prompt = "Enter height (inches): "))
height_cm <- height*2.54
weight <- strtoi(readline(prompt = "Enter weight(lbs): "))
weight_kg <- weight * 0.45359237
print("sed - little or no exercise")
print("light - exercise 1-3 times/week")
print("moderate - exercise 4-5 times/week")
print("active - daily exercise or intense exercise 3-4 times / week")
print("very active - intense exercise 6-7 times/week")
print("extra active - very intense exercise daily, or physical job")

activity <- tolower(readline(prompt = "Level of activity: "))
goal <- strtoi(readline(prompt = "How much weight do you want to lose in 1 week: "))
```

```{r}
bmr = round(10 * weight_kg + 6.25 * height_cm - 5 * age)
if (gender == "m"){
  bmr =  bmr + 5
} else if (gender == "f") {
  bmr = bmr - 161
} else {
  Print("invalid entry")
}
if (activity == "sed"){
  bmr = bmr
} else if (activity == "light"){
  bmr = bmr * 1.2
} else if (activity == "moderate"){
  bmr = bmr * 1.4
} else if (activity == "active"){
  bmr = bmr * 1.6
} else if (activity == "very active"){
  bmr = bmr * 1.8
} else if (activity == "extra active"){
  bmr = bmr * 2
} else {
  print("invalid entry2")
}

bmr = bmr - goal * 500

protein <- strtoi(readline(prompt = "perentage of calories from protein: "))
carbs <- strtoi(readline(prompt = "percentage of calories from carbs: "))
fat <- 100 - protein - carbs

protein_g <- protein*.01*bmr/4
carbs_g <- carbs*.01*bmr/4
fat_g <- fat*.01*bmr/9

fiber <- 33.6
satfat <- bmr*.1/9
calcium <- 1000
iron <- 8
magnesium <- 400
phosphorus <- 700
potassium <- 4700
sodium <- 2300
zinc <- 11
copper <- 900
manganese <- 2.3
selenium <- 55
vitA <- 900
vitE <- 15
vitD <- 600
vitC <- 90
thiamin <- 1.2
riboflavin <- 1.3
niacin <- 16
vitB6 <- 1.3
vitB12 <- 2.4
choline <- 550
vitK <- 120
folate <- 400
sugar <- bmr*.1/4
```

```{r lpsolve}
lpmodel <-list()
## Set the coefficients of the decision variables -> C
lpmodel$C <- c(rep(0, times = nrow(nutrition)))

# Create constraint martix B
lpmodel$A <- matrix(c(c(nutrition$Protein),
                      c(nutrition$`Calcium, Ca`),
                      c(nutrition$`Carbohydrate, by difference`),
#                      c(nutrition$Cholesterol),
                      c(nutrition$`Fatty acids, total saturated`),
#                      c(nutrition$Fatty.acids..total.trans),
                      c(nutrition$`Fiber, total dietary`),
                      c(nutrition$`Iron, Fe`),
                      c(nutrition$`Sodium, Na`),
                      c(nutrition$`Sugars, total`),
                      c(nutrition$`Total lipid (fat)`),
                      c(nutrition$`Vitamin A, IU`),
                      c(nutrition$`Vitamin B-12`),
                      c(nutrition$`Vitamin C, total ascorbic acid`),
                      c(nutrition$`Vitamin D`),
                      c(nutrition$`Vitamin E`),
                      c(nutrition$`Zinc, Zn`),
                      c(nutrition$Energy),
                      c(rep(1,times = nrow(nutrition)))),
                      nrow = 17, ncol=nrow(nutrition), byrow=T)


# Right hand side for the constraints
lpmodel$B <- c(protein_g,calcium, carbs_g, satfat, fiber, iron, sodium, sugar, fat_g, vitA, vitB12, vitC, vitD, vitE, zinc, bmr, 3)

# Direction of the constraints
lpmodel$constranints_direction  <- c(">=", ">", ">=", "<=", ">", ">", "<", "<", "<=", ">", ">", ">", ">", ">", ">", "=", "<=")

# Find the optimal solution
optimum <-  lp(direction="max",
               objective.in = lpmodel$C,
               const.mat = lpmodel$A,
               const.dir = lpmodel$constranints_direction,
               const.rhs = lpmodel$B)#,s
#               all.int = T)

# Print status: 0 = success, 2 = no feasible solution
print(optimum$status)

# Display the optimum values for x_4p, x_3p and x_w
best_sol <- optimum$solution
#names(best_sol) <- 
#print(best_sol)
index <- list()
amount <- list()
total = 0
count = 1
for (i in best_sol) {
  total = total +1
  if (i != 0){
    index <- c(index, total)
    amount <- c(amount, i)
    #index[count] <- total
    #amount[count] <- i
    #count = count +1
  }
}
print(index)
print(amount)

# Check the value of objective function at optimal point
#print(paste("Total cost: ", optimum$objval, sep=""))

```


```{r gurobi}
model <- list()
model$A = matrix(c(c(nutrition$Protein),
                      c(nutrition$`Calcium, Ca`),
                      c(nutrition$`Carbohydrate, by difference`),
#                      c(nutrition$Cholesterol),
                      c(nutrition$`Fatty acids, total saturated`),
#                      c(nutrition$Fatty.acids..total.trans),
                      c(nutrition$`Fiber, total dietary`),
                      c(nutrition$`Iron, Fe`),
                      c(nutrition$`Sodium, Na`),
                      c(nutrition$`Sugars, total`),
                      c(nutrition$`Total lipid (fat)`),
                      c(nutrition$`Vitamin A, IU`),
                      c(nutrition$`Vitamin B-12`),
                      c(nutrition$`Vitamin C, total ascorbic acid`),
                      c(nutrition$`Vitamin D`),
                      c(nutrition$`Vitamin E`),
                      c(nutrition$`Zinc, Zn`),
                      c(nutrition$Energy),
                      c(rep(1,times = nrow(nutrition)))),
                      nrow = 17, ncol=nrow(nutrition), byrow=T)

model$obj = c(rep(0, times = nrow(nutrition))) #Maximize n 
model$modelsense = "max" 
model$rhs = c(protein_g,calcium, carbs_g, satfat, fiber, iron, sodium, sugar, fat_g, vitA, vitB12, vitC, vitD, vitE, zinc, bmr, 3)
model$sense = c(">=", ">", ">=", "<=", ">", ">", "<", "<", "<=", ">", ">", ">", ">", ">", ">", "=", "<=")
model$vtype = 'C' #Continuous, nonnegative by default
params = list(OutputFlag=0)
result = gurobi(model, params)

#result$objval #Number of customer served, 797.6 
#result$x #Food to buy

gurindex <- list()
guramount <- list()
total = 0
count = 1
for (i in result$x) {
  total = total +1
  if (i != 0){
    gurindex <- c(gurindex, total)
    guramount <- c(guramount, i)
    #index[count] <- total
    #amount[count] <- i
    #count = count +1
  }
}
print(gurindex)
print(guramount)
```

```{r lpsolveapi}
#create an LP model with 10 constraints and 12 decision variables
 
 

matrixapi <- matrix(c(c(nutrition$Protein),
                      c(nutrition$`Calcium, Ca`),
                      c(nutrition$`Carbohydrate, by difference`),
#                      c(nutrition$Cholesterol),
                      c(nutrition$`Fatty acids, total saturated`),
#                      c(nutrition$Fatty.acids..total.trans),
                      c(nutrition$`Fiber, total dietary`),
                      c(nutrition$`Iron, Fe`),
                      c(nutrition$`Sodium, Na`),
                      c(nutrition$`Sugars, total`),
                      c(nutrition$`Total lipid (fat)`),
                      c(nutrition$`Vitamin A, IU`),
                      c(nutrition$`Vitamin B-12`),
                      c(nutrition$`Vitamin C, total ascorbic acid`),
                      c(nutrition$`Vitamin D`),
                      c(nutrition$`Vitamin E`),
                      c(nutrition$`Zinc, Zn`),
                      c(nutrition$Energy),
                      c(rep(1,times = nrow(nutrition)))),
                      nrow = 17, ncol=nrow(nutrition), byrow=T)
lpmodelapi<-make.lp(nrow = nrow(matrixapi), ncol = ncol(matrixapi))

#I used this to keep count within the loops, I admit that this could be done a lot neater
column<-0
row<-0
#build the model column per column
for(wg in 1:ncol(matrixapi)){
  set.column(lpmodelapi, wg, matrixapi[,wg])
}
 
#set rhs weight constraints
set.constr.value(lpmodelapi, rhs=c(protein_g,calcium, carbs_g, satfat, fiber, iron, sodium, sugar, fat_g, vitA, vitB12, vitC, vitD, vitE, zinc, bmr, 3), constraints=seq(1,NROW(matrixapi)))
 
#set objective coefficients
set.objfn(lpmodelapi, obj = rep(0, ncol(matrixapi)))

#set objective direction
lp.control(lpmodelapi,sense='max')
 
#I in order to be able to visually check the model, I find it useful to write the model to a text file
write.lp(lpmodelapi,'model.lp',type='lp')

#solve the model, if this return 0 an optimal solution is found
solve(lpmodelapi)
 
#this return the proposed solution
get.objective(lpmodelapi)

apiresult <-get.primal.solution(lpmodelapi)

apiindex <- list()
apiamount <- list()
total = 0
count = 1
for (n in apiresult) {
  total = total +1
  if (i != 0){
    apiindex <- c(apiindex, total)
    apiamount <- c(apiamount, i)
    #index[count] <- total
    #amount[count] <- i
    #count = count +1
  }
}
apiamount
apiindex
```
