---
title: "DA401"
author: "Alex Barnes"
date: "March 3, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lpSolve)
library(lpSolveAPI)
```

```{r}
nutrition <- read.csv("C:/users/alex/OneDrive/Documents/DA401/data/BFPD_csv_07132018/nutrient.csv")
nutrition <- subset(nutrition, select = -c(X))
age <- strtoi(readline(prompt = "Enter age: "))
gender <- tolower(readline(prompt = "Enter sex(m/f): "))
height <- strtoi(readline(prompt = "Enter height (inches): "))
height_cm <- height*2.54
weight <- strtoi(readline(prompt = "Enter weight(lbs): "))
weight_kg <- weight * 0.45359237
print("sed - little or no exercise")
print("light - exercise 1-3 times/week")
print("moderate - exercise 4-5 times/week")
print("active - daily exercise or intense exercise 3-4 times / week")
print("very active - intense exercise 6-7 times/week")
print("extra active - very intense exercise daily, or physical job")

activity <- tolower(readline(prompt = "Level of activity: "))
goal <- strtoi(readline(promtpt = "How much weight do you want to lose in 1 week: "))
```

```{r}
bmr = round(10 * weight_kg + 6.25 * height_cm - 5 * age)
if (gender == "m"){
  bmr =  bmr + 5
} else if (gender == "f") {
  bmr = bmr - 161
} else {
  Print("invalid entry")
}

```

```{r}
## Set the coefficients of the decision variables -> C
C <- c(30, 40, 80)

# Create constraint martix B
A <- matrix(c(1, 1, -10,
              4, 3, -20,
              1, 0, -2,
              1, 1, 0), nrow=4, byrow=TRUE)

# Right hand side for the constraints
B <- c(500, 200, 100, 1000)

# Direction of the constraints
constranints_direction  <- c("<=", "<=", "<=", ">=")

# Find the optimal solution
optimum <-  lp(direction="min",
               objective.in = C,
               const.mat = A,
               const.dir = constranints_direction,
               const.rhs = B,
               all.int = T)

# Print status: 0 = success, 2 = no feasible solution
print(optimum$status)

# Display the optimum values for x_4p, x_3p and x_w
best_sol <- optimum$solution
names(best_sol) <- c("x_4p", "x_3p", "x_w") 
print(best_sol)

# Check the value of objective function at optimal point
print(paste("Total cost: ", optimum$objval, sep=""))

```
